---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[cloudwatch-monitor::install]
      - recipe[cloudwatch-monitor::config]
    verifier:
      inspec_tests:
        - test/integration/install
        - test/integration/config
    attributes:
